spring:
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: jdbc:postgresql://${DATABASE_URL:database-1.cagaasqrhawk.us-east-2.rds.amazonaws.com}:${DATABASE_PORT:5432}/onlineorder
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATBASE_PASSWORD:XJJmylove520}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: ${INIT_DB:always}
      schema-locations: "classpath:database-init.sql"
  cache:
    caffeine:
      spec: expireAfterWrite=60s


logging:
  level:
    org.apache.coyote.http11.Http11InputBuffer: TRACE # Incoming HTTP requests
    org.springframework.jdbc.datasource.init: DEBUG # Database initialization
    org.springframework.jdbc.core: DEBUG # SQL
